const DOMSelectors = {
  moreButton: document.querySelector(".morebtn"),
  storyArea: document.querySelector(".storyarea"),
  settingCards: document.querySelector(".settingbox-cards"),
  settingInput: document.querySelector(".settingbox-setting-input"),
  monsterBox: document.querySelector("#monsterbox"),
  selectedBox: document.querySelector(".selected-box"),
  cardBox: document.querySelector(".card-box"),
  emptyIcon: document.querySelector(".fa-dragon"),
  searchForm: document.querySelector(".search-form"),
  searchBox: document.querySelector(".monster-search"),
  resetButton: document.querySelector(".search-reset"),
  monsterPopup: document.querySelector(".monster-popup"),
  closeIcon: document.querySelector(".fa-times"),
  characterBox: document.querySelector("#characterbox"),
  character: document.querySelector(".character"),
  raceSelect: document.querySelector(".race-select"),
  classSelect: document.querySelector(".class-select"),
  characterButton: document.querySelector(".addbutton"),
  deleteButton: document.querySelector(".deletebutton"),
  characterAndAdd: document.querySelector(".character-and-add"),
  iconBox: document.querySelector(".icon-box"),
  icon: document.querySelector(".selected-box-two"),
};
export { DOMSelectors };
