const DOMSelectors = {
  moreButton: document.querySelector(".morebtn"),
  storyArea: document.querySelector(".storyarea"),
  settingHeader: document.querySelector(".settingbox-card-heading"),
  settingInfo: document.querySelector(".settingbox-card-information"),
  settingAdd: document.getElementsByClassName(".settingbox-card-add"),
  monsterBox: document.querySelector("#monsterbox"),
  selectedBox: document.querySelector(".selected-box"),
  cardBox: document.querySelector(".card-box"),
  emptyIcon: document.querySelector(".fa-dragon"),
  searchForm: document.querySelector(".search-form"),
  searchBox: document.querySelector(".monster-search"),
  resetButton: document.querySelector(".search-reset"),
  monsterPopup: document.querySelector(".monster-popup"),
  closeIcon: document.querySelector(".fa-times"),
  character: document.querySelector(".character"),
  raceBox: document.querySelector(".race-box"),
  classBox: document.querySelector(".class-box"),
  characterButton: document.querySelector(".addbutton"),
  deleteButton: document.querySelector(".deletebutton"),
};
export { DOMSelectors };
